spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springHibernateDb
    username: postgres
    password: 7257
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled=true:
