spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teamEmployeesDb
    username: postgres
    password: 7257
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled=true:
